import { GuesserModelN } from "../../types/model.js";
import { EmbedBuilder } from "discord.js";

export default class GuesserModelEmebds {
  public static results(data: GuesserModelN.EmbedReportDataT) {
    return new EmbedBuilder()
      .setAuthor({
        name: "Daily 3 - Guesser Model",
      })
      .setTitle("Guesser Model Analysis Results")
      .addFields(
        {
          name: "Positional Statistics (Top 3)",
          value: "```\n" + data.byPositionReport + "```",
          inline: false,
        },
        {
          name: "Sequential Statistics (Top 6)",
          value: "```\n" + data.bySequenceReport + "```",
          inline: false,
        },
        {
          name: "Pattern Statistics (Top 6)",
          value: "```\n" + data.byPatternReport + "```",
          inline: false,
        },
        {
          name: "Latest 10 Draws",
          value: "```\n" + data.latestTop10Draws + "```",
          inline: false,
        },
      )
      .setColor("#f56e00")
      .setFooter({
        text: "Generated by Calottery Guesser Module",
      })
      .setTimestamp();
  }
}
